- name: create ec2 instance and dns
  hosts: all
  connection: local
  sg: 08290382adsd-a93232asd
  id: 98823adjdk2121234f
  instance:
    - mongodb
    - catalogue
  env: qa

  tasks:
    ansible.aws.ec2_instance:
      instance_type: t3.micro
      security_group: "{{ sg }}"
      image_id: "{{ id }}"
      name: "{{ item }}-{{env}}"
    tags:
      name: robshop 
      

