[mongodb]
mongodb-dev.cerry.in

[catalogue]
catalogue-dev.cerry.in

[redis]
redis-dev.cerry.in

[user]
user-dev.cerry.in

[cart]
cart-dev.cerry.in

[mysql]
mysql-dev.cerry.in

[shipping]
172.31.14.53

[payment]
payment-dev.cerry.in

[frontend]
frontend-dev.cerry.in

[rabbitmq]
rabbitmq-dev.cerry.in

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.cerry.in
REDIS_HOST=redis-dev.cerry.in
USER_HOST=user-dev.cerry.in
CATALOGUE_HOST=catalogue-dev.cerry.in
CART_HOST=cart-dev.cerry.in
MYSQL_HOST=mysql-dev.cerry.in
SHIPPING_HOST=172.31.14.53
RABBITMQ_HOST=rabbitmq-dev.cerry.in
PAYMENT_HOST=payment-dev.cerry.in